#PBS -N killms
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2600mb
#PBS -l walltime=48:00:00
#PBS -k oe
#PBS -q smp

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: ARRAYID = $PBS_ARRAYID
echo ------------------------------------------------------

module load casa
module load lofar
source /soft/lofar-091114/lofarinit.csh
setenv PATH /home/mjh/lofar/bin:$PATH
setenv PYTHONPATH /home/tasse/bin/lib64/python2.7/site-packages:/soft/pyrap:$PYTHONPATH
setenv LD_LIBRARY_PATH /home/tasse/bin/lib:$LD_LIBRARY_PATH

/home/mjh/lofar/surveys-pipeline/killms.py $CONFIG $PBS_ARRAYID
